apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "track-promises.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "track-promises.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "track-promises.name" . }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: NEXTAUTH_URL
              value: {{ .Values.env.NEXTAUTH_URL | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
