apiVersion: v1
kind: Service
metadata:
  name: {{ include "track-promises.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "track-promises.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
