replicaCount: 1

image:
  tag: local

ingress:
  enabled: false
  host: track-promises.localhost
  wildcardHost: "*.track-promises.localhost"

env:
  NEXTAUTH_URL: http://track-promises.localhost:3000